name: units
parameters: |
  __spring.xml=xharbor/xharbor.xml,http/httpclient.xml
children:
  - name: nettystats
  - name: redisclient
    parameters: |
      redis.server.hostname=localhost
      redis.server.passwd=passwd
      redis.server.dbno=255
  - name: conf
    children:
      - name: conf_setting.stream_rbs
        parameters: |
          path= /newrest/
          key = rbs
          value = true
  - name: jmxsrv
    parameters: |
      jmxmp.port = 0
      jmxhtml.port = 8083
  - name: nop.httpout
    children:
      - name: httpfeatures.compress
        parameters: |
          features.name=compress
        children:
          - name: feature_compress
          - name: feature_logging
      - name: httpfeatures.default
        parameters: |
          features.name=default
#        children:
#          - name: feature_logging
  - name: router.biz
    children:
      - name: httpserver.biz
        parameters: |
          http.server.inbound.blocksize = 8192
          http.server.inbound.recvbuf = 8192
        children:
          - name: httpin.8888
            parameters: |
              http.port=8888
              http.address=127.0.0.1
          - name: httpin.8443_https
            parameters: |
              http.port=8443
              http.address=127.0.0.1
            children:
              - name: feature_ssl4server
      - name: rules.100
        parameters: |
          priority=100
        children:
          - name: forward.newrest
            parameters: |
              forward.path=/newrest/
              forward.to=http://127.0.0.1:9090
              features.name=default
          - name: forward.live
            parameters: |
              forward.path=/demo/
              forward.to=http://live.iplusmed.com:80
              features.name=default
          - name: rwreq.live
            parameters: |
              rewrite.path=/demo/
              rewrite.header.name=Host
              rewrite.header.value=live.iplusmed.com
          - name: forward.crossdomain
            parameters: |
              forward.path=/crossdomain.xml
              forward.to=http://wapp.jocean.org:80
              features.name=default
          - name: rwreq.crossdomain
            parameters: |
              rewrite.path=/crossdomain.xml
              rewrite.header.name=Host
              rewrite.header.value=wapp.jocean.org
          - name: respond.checkhealth
            parameters: |
              request.method=HEAD|GET
              request.path=^/$|/checkhealth
              response.status=200
          - name: forward.ydd
            parameters: |
              forward.path=/api1/|/api2/
              
              forward.to=http://api.iplusmed.com:80
              features.name=compress
          - name: forward.snsgw
            parameters: |
              forward.path=/test/
              
              forward.to=http://127.0.0.1:9090
              features.name=default
          - name: forward.zkwebui
            parameters: |
              forward.path=/zkwebui/
              forward.to=http://127.0.0.1:7080
          - name: rwresp.cors
            parameters: |
              rewrite.path=/api1/
            children:
              - name: addheader.cors.basic
                parameters: |
                  header.name=Access-Control-Allow-Origin
                  header.value=*
#      - name: rules.200
#        parameters: |
#          priority=200
#        children:
#          - name: respond.reject_missctx
#            parameters: |
#              request.path=/newrest/stream
#              request.headers=x-ctx,==null
#              response.status = 404
#      - name: rules.300
#        parameters: |
#          priority=300
#        children:
#          - name: drop.reject_missctx
#            parameters: |
#              request.path=/newrest/stream
#              request.headers=x-ctx,==null
  - name: router.console
    children:
      - name: httpserver.console
        parameters: |
          http.server.inbound.blocksize = 8192
          http.server.inbound.recvbuf = 8192
        children:
          - name: httpin.8889
            parameters: |
              http.port=8889
            children:
              - name: feature_logging
      - name: rules.100
        parameters: |
          priority=100
          in.maxBPS = 1024
        children:
          - name: forward.jmxhtml.self
            parameters: |
              forward.headers=x-jmx,jmxhtml.self
              forward.to=http://127.0.0.1:8083
          - name: rwreq.jmxhtml
            parameters: |
              rewrite.path=/jmxhtml/
              rewrite.to=/
              rewrite.header.name=x-jmx
              rewrite.header.value=jmxhtml.self
          - name: auth.jmxhtml
            parameters: |
              auth.headers=x-jmx,jmxhtml(\\w)*
              auth.user=test
              auth.password=test
              